specialty: "Emergency Medicine"
model_size: "xlarge"
status: "near-complete"
lexical_policy: "real_terms_only"
description: "Emergency Medicine XL – deep trauma, toxicology, imaging findings, abbreviations, and dictation phrases"
