specialty: "Emergency Medicine"
model_size: "xlarge"
status: "in-progress"
lexical_policy: "real_terms_only"
description: "Emergency Medicine XL – combined trauma, toxicology, labs, imaging, devices, abbreviations, and dictation phrases"
