specialty: "Radiology"
model_size: "large"
source: "Dragon vocabulary mapping (conceptual)"
version: "1.0.0"
status: "placeholder"
note: "May overlap with existing specialty; duplication allowed safely"
